@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

Container(cAndroid, "Android Application", "Kotlin", "Logs various trucker sensor data and transmits to data store")
ContainerDb(db, "Database", "MySQL", "Store logged sensor data for fleet, companies and managers", $sprite="msql_server")

Container_Boundary(cIO, "I/O Server" ) {
    Component(server, "Server", "Singleton server object", "Listens for incoming connections on the set port.")
    Component(session, "Session", "Newly instatiated by the Server for connection lifetime", "Handles SSL handshake, SSL encryption/decryption and sending/receiving data streams.")
    Component(requestHandler, "Request Handler", "Handler", "Parses json request and generates appropriate response.")
    Component(sql, "MySQL Connector", "mysql++", "Provides database operations")
}

Rel_R(cAndroid,server, "transmits request data to", "SSL")
Rel_L(server,cAndroid, "transmits response data to", "SSL")

Rel_R(server,session, "assigns session to connection with payload data")
Rel(session,requestHandler, "transmits serialized request payload")
Rel(requestHandler, session, "transmits serialized response payload")
Rel_R(requestHandler,sql, "issues database transaction")
Rel_R(sql,db, "writes to/reads from")

@enduml
