@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

Container(cAndroid, "Android Application", "Kotlin", "Logs various trucker sensor data and transmits to data store")
ContainerDb(db, "Database", "MySQL", "Store logged sensor data for fleet, companies and managers", $sprite="msql_server")

Container_Boundary(cIO, "I/O Server" ) {
    Component(RequestHandler, "Request Handler", "MVC Rest Controller", "Process client request")
    Component(FleetController, "Fleet Controller", "MVC Rest Controller", "Controller for fleet records")
}

Rel(cAndroid, RequestHandler, "sends API requests", "JSON/SSL")
Rel_R(RequestHandler, FleetController, "sends API requests", "JSON")
Rel(FleetController, db, "Update/select data", "DB Connector")

@enduml
