!theme spacelab
@startjson
{
    "data": [
        {
            "acc": 0.18192993,
            "alt": 1376.5499,
            "id": 23312,
            "lat": -26.70164,
            "lon": 27.086374,
            "spd": 0.09585135,
            "tim": 1633541355
        },
        {
            "acc": 0.07141463,
            "alt": 1376.4137,
            "id": 23325,
            "lat": -26.701616,
            "lon": 27.086409,
            "spd": 0.4677902,
            "tim": 1633541478
        }
    ],
    "id": 1,
    "req": 3,
    "uuid": "4fa0084c-fa7a-40a9-8f02-60e636766c90"
}
@endjson
